#!/bin/sh
 pdfmerge freeEMS_1.pdf\
 power_reg2.pdf\
 power_reg1.pdf\
 digi_protect_I1.pdf\
 digi_protect_I2.pdf\
 digi_protect_I3.pdf\
 digi_protect_I4.pdf\
 digi_protect_I5.pdf\
 digi_protect_I6.pdf\
 ignition6.pdf\
 ignition5.pdf\
 ignition4.pdf\
 ignition3.pdf\
 ignition2.pdf\
 ignition1.pdf\
 MAP_input2.pdf\
 MAP_input1.pdf\
 digi_protect_rpm1.pdf\
 digi_protect_rpm2.pdf\
 digi_protect_fuel.pdf\
 digi_protect_misc1.pdf\
 an_protect2.pdf\
 an_protect4.pdf\
 O2_input.pdf\
 general_drive2.pdf\
 general_drive1.pdf\
 digi_protect_misc2.pdf\
 general_drive_fuel.pdf\
 injector_drive1.pdf\
 injector_drive2.pdf\
 injector_drive3.pdf\
 injector_drive4.pdf\
 injector_drive5.pdf\
 injector_drive6.pdf\
 RPM_input2.pdf\
 RPM_input1.pdf\
 BAT_condition.pdf\
 TPS_input.pdf\
 thermistor_resistor_input2.pdf\
 thermistor_resistor_input1.pdf\
 CPU.pdf\
 freeEMS_1-Component.pdf\
 freeEMS_1-Copper.pdf\
 freeEMS_1-SilkSCmp.pdf\
 freeEMS_1-SilkSCop.pdf\
 freeEMS_1_combined-full_A.20.pdf
